version: "3.8"

services:
  db:
    image: registry.zdrive.ir/postgres:15
    container_name: odoo_db
    environment:
      POSTGRES_DB: burna
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d burna"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - odoo_net

  odoo:
    image: ghcr.io/odoo/odoo:19.2
    container_name: odoo_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: odoo
      DB_PASSWORD: odoo
      DB_NAME: burna
      ODOO_ADMIN_EMAIL: mahanbabelian@gmail.com
      ODOO_ADMIN_PASSWORD: mahan1234
      ODOO_DEBUG: "true"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - odoo-web-data:/var/lib/odoo
      - ./entrypoint/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
    command: ["--dev", "all", "--update", "all", "--stop-after-init"]
    ports:
      - "8069:8069"
      - "7777:7777"
    restart: always
    networks:
      - odoo_net



volumes:
  odoo-db-data:
  odoo-web-data:


networks:
  odoo_net:
    driver: bridge